apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joomla-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# kubectl apply -f pvc-joomla.yml
# kubectl get pvc
